### ISSUE TITLE
Next.js synth build fails

### ISSUE THREAD

**Issue by TimPaisley** [WellingtonCityCouncil/Demos.CDKApiPipeline#1]
When attempting to build the Next.js app in the `/website` directory, the CodeBuildStep synth fails because it `couldn't find a 'pages' directory`.

### PipelineStack.js
```javascript
const synthAction = new pipelines.CodeBuildStep("Synth", {
  input: pipelines.CodePipelineSource.gitHub(`${repoOwner}/${repoName}`, "main", {
    authentication: cdk.SecretValue.secretsManager("GitHubToken"),
  }),
  installCommands: [
    'npm install',
    'npm run install-website'
  ],
  commands: [
    'npm run build',
    'npm run build-website',
    // 'npm test',
    'npm audit --audit-level=critical',
    'npx cdk synth',
  ],
  primaryOutputDirectory: 'cdk.out',
  partialBuildSpec: codebuild.BuildSpec.fromObject({
    reports: {
      [testReports.reportGroupArn]: {
        files: [
          '**/test-report.xml',
        ],
        'discard-paths': true,
      }
    },
  }),
  env: {
    'DEV_ACCOUNT': process.env.DEV_ACCOUNT || '',
    'PROD_ACCOUNT': process.env.PROD_ACCOUNT || '',
    'REPO_NAME': process.env.REPO_NAME || '',
    'DOMAIN_NAME': process.env.DOMAIN_NAME || '',
    'DEVOPS_ACCOUNT': process.env.DEVOPS_ACCOUNT || '',
  },
});
```
### package.json
```javascript
"scripts": {
  "build": "tsc",
  "install-website": "cd website && npm install && cd ..",
  "build-website": "cd website && npm run build && cd ..",
  "watch": "tsc -w",
  "test": "jest",
  "cdk": "cdk",
  // ...
},
```

### Pipeline logs
```
[Container] 2021/11/10 03:53:21 Running command npm run build-website
--
 
> @demos/cdkapipipeline@1.0.0 build-website /codebuild/output/src182428796/src
> cd website && npm run build && cd ..
 
 
> @ build /codebuild/output/src182428796/src/website
> next build && next export
 
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
 
 
> Build error occurred
Error: > Couldn't find a `pages` directory. Please create one under the project root
at Object.findPagesDir (/codebuild/output/src182428796/src/website/node_modules/next/dist/lib/find-pages-dir.js:33:11)
at /codebuild/output/src182428796/src/website/node_modules/next/dist/build/index.js:114:45
at async Span.traceAsyncFn (/codebuild/output/src182428796/src/website/node_modules/next/dist/trace/trace.js:74:20)
at async Object.build [as default] (/codebuild/output/src182428796/src/website/node_modules/next/dist/build/index.js:82:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `next build && next export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
```

**Comment by TimPaisley** [comment]
Ah, turns out `/pages` was in fact not in the repo, I had to adjust `!website/*` to `!website/**/*` to the `.gitignore` so all the pages and components were uploaded to the repo as well.
